services:
  - type: web
    name: inventory-api
    runtime: docker
    repo: https://github.com/SurajG20/inventory-order-management
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inventory-db
          property: connectionString

databases:
  - name: inventory-db
    plan: free
    postgresMajorVersion: 15
